/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/models/table.glb -type 
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Avalon_160_80_table: THREE.Mesh
    Mesh065: THREE.Mesh
    Mesh065_1: THREE.Mesh
    Mesh065_2: THREE.Mesh
    Mesh065_3: THREE.Mesh
    Mesh065_4: THREE.Mesh
    Mesh065_5: THREE.Mesh
    Mesh065_6: THREE.Mesh
    Mesh065_7: THREE.Mesh
    Mesh065_8: THREE.Mesh
    Mesh065_9: THREE.Mesh
    Mesh065_10: THREE.Mesh
    Mesh065_11: THREE.Mesh
    Mesh065_12: THREE.Mesh
    Mesh065_13: THREE.Mesh
    Mesh065_14: THREE.Mesh
    Mesh066: THREE.Mesh
    Mesh066_1: THREE.Mesh
    Mesh066_2: THREE.Mesh
    Mesh066_3: THREE.Mesh
    Mesh066_4: THREE.Mesh
    Mesh067: THREE.Mesh
    Mesh067_1: THREE.Mesh
    Mesh067_2: THREE.Mesh
    Mesh068: THREE.Mesh
    Mesh068_1: THREE.Mesh
    Mesh068_2: THREE.Mesh
    Mesh069: THREE.Mesh
    Mesh069_1: THREE.Mesh
    Mesh069_2: THREE.Mesh
    Mesh070: THREE.Mesh
    Mesh070_1: THREE.Mesh
    Mesh070_2: THREE.Mesh
    Mesh070_3: THREE.Mesh
    Mesh070_4: THREE.Mesh
    Mesh070_5: THREE.Mesh
    Mesh070_6: THREE.Mesh
    Mesh070_7: THREE.Mesh
    Mesh070_8: THREE.Mesh
    Mesh070_9: THREE.Mesh
    Mesh070_10: THREE.Mesh
    Mesh070_11: THREE.Mesh
    Mesh070_12: THREE.Mesh
    Mesh071: THREE.Mesh
    Mesh071_1: THREE.Mesh
    Mesh071_2: THREE.Mesh
    Mesh071_3: THREE.Mesh
    Mesh071_4: THREE.Mesh
    Mesh071_5: THREE.Mesh
    Mesh071_6: THREE.Mesh
    Mesh071_7: THREE.Mesh
    Mesh071_8: THREE.Mesh
    Mesh071_9: THREE.Mesh
    Mesh071_10: THREE.Mesh
    Mesh071_11: THREE.Mesh
    Mesh071_12: THREE.Mesh
    Mesh071_13: THREE.Mesh
    Mesh071_14: THREE.Mesh
    Mesh071_15: THREE.Mesh
    Mesh071_16: THREE.Mesh
    Mesh071_17: THREE.Mesh
    Mesh071_18: THREE.Mesh
    Mesh071_19: THREE.Mesh
    Mesh072: THREE.Mesh
    Mesh072_1: THREE.Mesh
    Mesh072_2: THREE.Mesh
    Mesh072_3: THREE.Mesh
    Mesh072_4: THREE.Mesh
    Mesh072_5: THREE.Mesh
    Mesh073: THREE.Mesh
    Mesh073_1: THREE.Mesh
    Mesh073_2: THREE.Mesh
    Mesh073_3: THREE.Mesh
    Mesh074: THREE.Mesh
    Mesh074_1: THREE.Mesh
    Mesh074_2: THREE.Mesh
    Mesh074_3: THREE.Mesh
    Mesh074_4: THREE.Mesh
    Mesh074_5: THREE.Mesh
    Mesh074_6: THREE.Mesh
    Mesh075: THREE.Mesh
    Mesh075_1: THREE.Mesh
    Mesh075_2: THREE.Mesh
    Mesh076: THREE.Mesh
    Mesh076_1: THREE.Mesh
    Mesh076_2: THREE.Mesh
    Mesh077: THREE.Mesh
    Mesh077_1: THREE.Mesh
    Mesh077_2: THREE.Mesh
    Apple_id1995: THREE.Mesh
    Mesh079: THREE.Mesh
    Mesh079_1: THREE.Mesh
    Mesh079_2: THREE.Mesh
    Mesh079_3: THREE.Mesh
    Mesh079_4: THREE.Mesh
    Mesh080: THREE.Mesh
    Mesh080_1: THREE.Mesh
    Mesh080_2: THREE.Mesh
    Mesh080_3: THREE.Mesh
    Mesh080_4: THREE.Mesh
    Mesh081: THREE.Mesh
    Mesh081_1: THREE.Mesh
    Mesh081_2: THREE.Mesh
    Mesh082: THREE.Mesh
    Mesh082_1: THREE.Mesh
    Mesh082_2: THREE.Mesh
    Mesh082_3: THREE.Mesh
    Mesh082_4: THREE.Mesh
    Mesh082_5: THREE.Mesh
    Mesh082_6: THREE.Mesh
    Mesh082_7: THREE.Mesh
    Mesh082_8: THREE.Mesh
    Mesh082_9: THREE.Mesh
    Mesh082_10: THREE.Mesh
    Mesh082_11: THREE.Mesh
    Mesh082_12: THREE.Mesh
    Mesh082_13: THREE.Mesh
    Mesh082_14: THREE.Mesh
    Mesh082_15: THREE.Mesh
    Mesh082_16: THREE.Mesh
    Mesh082_17: THREE.Mesh
    Mesh082_18: THREE.Mesh
    Mesh083: THREE.Mesh
    Mesh083_1: THREE.Mesh
    Mesh083_2: THREE.Mesh
    Mesh083_3: THREE.Mesh
    Mesh083_4: THREE.Mesh
    Mesh083_5: THREE.Mesh
    Mesh083_6: THREE.Mesh
    Mesh083_7: THREE.Mesh
    Table_1: THREE.Mesh
    Mesh085: THREE.Mesh
    Mesh085_1: THREE.Mesh
    Mesh085_2: THREE.Mesh
    Mesh086: THREE.Mesh
    Mesh086_1: THREE.Mesh
    Mesh086_2: THREE.Mesh
    Mesh086_3: THREE.Mesh
    Mesh086_4: THREE.Mesh
    Mesh087: THREE.Mesh
    Mesh087_1: THREE.Mesh
    Mesh087_2: THREE.Mesh
    Mesh087_3: THREE.Mesh
  }
  materials: {
    ['vray Apple id22.003']: THREE.MeshStandardMaterial
    ['vray Apple id23.003']: THREE.MeshStandardMaterial
    ['vray Apple id24.003']: THREE.MeshStandardMaterial
    ['vray Apple id25.003']: THREE.MeshStandardMaterial
    ['vray Apple id26.003']: THREE.MeshStandardMaterial
    ['vray Apple id27.003']: THREE.MeshStandardMaterial
    ['vray Apple id28.003']: THREE.MeshStandardMaterial
    ['vray Apple id32.003']: THREE.MeshStandardMaterial
    ['vray Apple id33.003']: THREE.MeshStandardMaterial
    ['vray Apple id34.003']: THREE.MeshStandardMaterial
    ['vray Apple id35.003']: THREE.MeshStandardMaterial
    ['vray Apple id36.003']: THREE.MeshStandardMaterial
    ['vray Apple id37.003']: THREE.MeshStandardMaterial
    ['vray Apple id38.003']: THREE.MeshStandardMaterial
    ['vray Apple id39.003']: THREE.MeshStandardMaterial
    ['vray Apple id89.003']: THREE.MeshStandardMaterial
    ['vray Apple id90.003']: THREE.MeshStandardMaterial
    ['vray Apple id91.003']: THREE.MeshStandardMaterial
    ['vray Apple id92.003']: THREE.MeshStandardMaterial
    ['vray Apple id93.003']: THREE.MeshStandardMaterial
    ['vray Pen 3.003']: THREE.MeshStandardMaterial
    ['vray Pen 4.003']: THREE.MeshStandardMaterial
    ['vray Pen 5.003']: THREE.MeshStandardMaterial
    ['vray Pen 22.003']: THREE.MeshStandardMaterial
    ['vray Pen 23.003']: THREE.MeshStandardMaterial
    ['vray Pen 24.003']: THREE.MeshStandardMaterial
    ['vray Apple id262.003']: THREE.MeshStandardMaterial
    ['vray Apple bn7.006']: THREE.MeshStandardMaterial
    ['vray Apple bn6.003']: THREE.MeshStandardMaterial
    ['vray Apple id854.003']: THREE.MeshStandardMaterial
    ['vray Apple id4.003']: THREE.MeshStandardMaterial
    ['vray Apple id5.003']: THREE.MeshStandardMaterial
    ['vray Apple id6.003']: THREE.MeshStandardMaterial
    ['vray Apple id7.003']: THREE.MeshStandardMaterial
    ['vray Apple id8.003']: THREE.MeshStandardMaterial
    ['vray Apple id9.003']: THREE.MeshStandardMaterial
    ['vray Apple id10.003']: THREE.MeshStandardMaterial
    ['vray Apple id11.003']: THREE.MeshStandardMaterial
    ['vray Apple Display.003']: THREE.MeshStandardMaterial
    ['vray Apple id15.003']: THREE.MeshStandardMaterial
    ['vray Apple id16.003']: THREE.MeshStandardMaterial
    ['vray Apple id17.003']: THREE.MeshStandardMaterial
    ['vray Apple id42.003']: THREE.MeshStandardMaterial
    ['vray Apple id43.003']: THREE.MeshStandardMaterial
    ['vray Apple id44.003']: THREE.MeshStandardMaterial
    ['vray Apple id48.003']: THREE.MeshStandardMaterial
    ['vray Apple id49.003']: THREE.MeshStandardMaterial
    ['vray Apple id50.003']: THREE.MeshStandardMaterial
    ['vray Apple id51.003']: THREE.MeshStandardMaterial
    ['vray Apple id52.003']: THREE.MeshStandardMaterial
    ['vray Apple id53.003']: THREE.MeshStandardMaterial
    ['vray Apple id54.003']: THREE.MeshStandardMaterial
    ['vray Apple id55.003']: THREE.MeshStandardMaterial
    ['vray Apple id56.003']: THREE.MeshStandardMaterial
    ['vray Apple id57 Display.003']: THREE.MeshStandardMaterial
    ['vray Apple id58.003']: THREE.MeshStandardMaterial
    ['vray Apple id59.003']: THREE.MeshStandardMaterial
    ['vray Apple id60.003']: THREE.MeshStandardMaterial
    ['vray Apple id61.003']: THREE.MeshStandardMaterial
    ['vray Apple id62.003']: THREE.MeshStandardMaterial
    ['vray Apple id63.003']: THREE.MeshStandardMaterial
    ['vray Apple id64.003']: THREE.MeshStandardMaterial
    ['vray Power 3.003']: THREE.MeshStandardMaterial
    ['vray Power 4.003']: THREE.MeshStandardMaterial
    ['vray Power 5.003']: THREE.MeshStandardMaterial
    ['vray Power 8.003']: THREE.MeshStandardMaterial
    ['vray Apple id256.003']: THREE.MeshStandardMaterial
    ['vray Apple id257.003']: THREE.MeshStandardMaterial
    ['vray Apple id258.003']: THREE.MeshStandardMaterial
    ['vray Apple id259.003']: THREE.MeshStandardMaterial
    ['vray Apple id251.003']: THREE.MeshStandardMaterial
    ['vray Apple bn7.007']: THREE.MeshStandardMaterial
    ['vray Apple bn6r.003']: THREE.MeshStandardMaterial
    ['vray Apple id252.003']: THREE.MeshStandardMaterial
    ['vray Apple TV 3.003']: THREE.MeshStandardMaterial
    ['vray Apple TV 4.003']: THREE.MeshStandardMaterial
    ['vray Apple TV 5.003']: THREE.MeshStandardMaterial
    ['vray Apple bn38.003']: THREE.MeshStandardMaterial
    ['vray Apple bn39.003']: THREE.MeshStandardMaterial
    ['vray Apple bn40.003']: THREE.MeshStandardMaterial
    ['vray Apple id19.003']: THREE.MeshStandardMaterial
    ['vray Airpods 32.003']: THREE.MeshStandardMaterial
    ['vray Airpods 33.003']: THREE.MeshStandardMaterial
    ['vray Airpods 34.003']: THREE.MeshStandardMaterial
    ['vray Airpods 35.003']: THREE.MeshStandardMaterial
    ['vray Airpods 36.003']: THREE.MeshStandardMaterial
    ['vray Airpods 22.003']: THREE.MeshStandardMaterial
    ['vray Airpods 23.003']: THREE.MeshStandardMaterial
    ['vray Airpods 24.003']: THREE.MeshStandardMaterial
    ['vray Airpods 25.003']: THREE.MeshStandardMaterial
    ['vray Airpods 26.003']: THREE.MeshStandardMaterial
    ['vray Galsses 911.003']: THREE.MeshStandardMaterial
    ['vray Galsses 912.003']: THREE.MeshStandardMaterial
    ['vray Apple Pro 3.001']: THREE.MeshStandardMaterial
    ['vray Apple Pro 4.001']: THREE.MeshStandardMaterial
    ['vray Apple Pro 7.001']: THREE.MeshStandardMaterial
    ['vray Apple Pro 10.001']: THREE.MeshStandardMaterial
    ['vray Apple Pro 11.001']: THREE.MeshStandardMaterial
    ['vray Apple Pro 12.001']: THREE.MeshStandardMaterial
    ['vray Apple Pro 13.001']: THREE.MeshStandardMaterial
    ['vray Apple Pro 14.001']: THREE.MeshStandardMaterial
    ['vray Apple Pro 15.001']: THREE.MeshStandardMaterial
    ['vray iphone 13 pro 11.001']: THREE.MeshStandardMaterial
    ['vray iphone 13 pro 15.001']: THREE.MeshStandardMaterial
    ['vray iphone 13 pro 16.001']: THREE.MeshStandardMaterial
    ['vray iphone 13 pro 23.001']: THREE.MeshStandardMaterial
    ['vray Apple Pro 20.001']: THREE.MeshStandardMaterial
    ['vray Apple Pro 21.001']: THREE.MeshStandardMaterial
    ['vray Apple Pro 22.001']: THREE.MeshStandardMaterial
    ['vray Apple Pro 23.001']: THREE.MeshStandardMaterial
    ['vray Apple Pro 24.001']: THREE.MeshStandardMaterial
    ['vray Apple Pro 42 Display.001']: THREE.MeshStandardMaterial
    ['vray Keyboard Apple 3.001']: THREE.MeshStandardMaterial
    ['vray Keyboard Apple 4.001']: THREE.MeshStandardMaterial
    ['vray Keyboard Apple 5.001']: THREE.MeshStandardMaterial
    ['vray Keyboard Apple 6.001']: THREE.MeshStandardMaterial
    ['vray Keyboard Apple 7.001']: THREE.MeshStandardMaterial
    ['vray Keyboard Apple 8.001']: THREE.MeshStandardMaterial
    ['vray Keyboard Apple 9.001']: THREE.MeshStandardMaterial
    ['vray Keyboard Apple 10.001']: THREE.MeshStandardMaterial
    ['vray Table 2.003']: THREE.MeshStandardMaterial
    ['vray HomePod Mini 3.003']: THREE.MeshStandardMaterial
    ['vray HomePod Mini 4.003']: THREE.MeshStandardMaterial
    ['vray HomePod Mini 5.003']: THREE.MeshStandardMaterial
    ['vray Headphones 3.003']: THREE.MeshStandardMaterial
    ['vray Headphones 4.003']: THREE.MeshStandardMaterial
    ['vray Headphones 5.003']: THREE.MeshStandardMaterial
    ['vray Headphones 9.003']: THREE.MeshStandardMaterial
    ['vray Headphones 10.003']: THREE.MeshStandardMaterial
    ['vray Mastercard 3.003']: THREE.MeshStandardMaterial
    ['vray Mastercard 4.003']: THREE.MeshStandardMaterial
    ['vray Mastercard 5.003']: THREE.MeshStandardMaterial
    ['vray Mastercard 6.003']: THREE.MeshStandardMaterial
  }
  // animations: GLTFAction[]
}

// type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Table(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/table.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Avalon_160_80_table.geometry} material={nodes.Avalon_160_80_table.material} position={[-0.123, 0.628, -9.218]} rotation={[1.584, -0.002, 0.015]} scale={[0.012, 0.011, 0.01]} />
      <group castShadow position={[7.216, 8.467, 2.132]} rotation={[-Math.PI, 0.004, -Math.PI]} scale={0.013}>
        <mesh geometry={nodes.Mesh065.geometry} material={materials['vray Apple id22.003']} />
        <mesh geometry={nodes.Mesh065_1.geometry} material={materials['vray Apple id23.003']} />
        <mesh geometry={nodes.Mesh065_2.geometry} material={materials['vray Apple id24.003']} />
        <mesh geometry={nodes.Mesh065_3.geometry} material={materials['vray Apple id25.003']} />
        <mesh geometry={nodes.Mesh065_4.geometry} material={materials['vray Apple id26.003']} />
        <mesh geometry={nodes.Mesh065_5.geometry} material={materials['vray Apple id27.003']} />
        <mesh geometry={nodes.Mesh065_6.geometry} material={materials['vray Apple id28.003']} />
        <mesh geometry={nodes.Mesh065_7.geometry} material={materials['vray Apple id32.003']} />
        <mesh geometry={nodes.Mesh065_8.geometry} material={materials['vray Apple id33.003']} />
        <mesh geometry={nodes.Mesh065_9.geometry} material={materials['vray Apple id34.003']} />
        <mesh geometry={nodes.Mesh065_10.geometry} material={materials['vray Apple id35.003']} />
        <mesh geometry={nodes.Mesh065_11.geometry} material={materials['vray Apple id36.003']} />
        <mesh geometry={nodes.Mesh065_12.geometry} material={materials['vray Apple id37.003']} />
        <mesh geometry={nodes.Mesh065_13.geometry} material={materials['vray Apple id38.003']} />
        <mesh geometry={nodes.Mesh065_14.geometry} material={materials['vray Apple id39.003']} />
      </group>
      <group castShadow position={[-1.292, 8.454, 4.899]} rotation={[-Math.PI, 0.004, -Math.PI]} scale={0.013}>
        <mesh geometry={nodes.Mesh066.geometry} material={materials['vray Apple id89.003']} />
        <mesh geometry={nodes.Mesh066_1.geometry} material={materials['vray Apple id90.003']} />
        <mesh geometry={nodes.Mesh066_2.geometry} material={materials['vray Apple id91.003']} />
        <mesh geometry={nodes.Mesh066_3.geometry} material={materials['vray Apple id92.003']} />
        <mesh geometry={nodes.Mesh066_4.geometry} material={materials['vray Apple id93.003']} />
      </group>
      <group castShadow position={[-2.836, 8.457, -0.245]} rotation={[-Math.PI, 0.004, -Math.PI]} scale={0.013}>
        <mesh geometry={nodes.Mesh067.geometry} material={materials['vray Pen 3.003']} />
        <mesh geometry={nodes.Mesh067_1.geometry} material={materials['vray Pen 4.003']} />
        <mesh geometry={nodes.Mesh067_2.geometry} material={materials['vray Pen 5.003']} />
      </group>
      <group castShadow position={[-2.646, 8.436, 0.134]} rotation={[-Math.PI, 0.004, -Math.PI]} scale={0.013}>
        <mesh geometry={nodes.Mesh068.geometry} material={materials['vray Pen 22.003']} />
        <mesh geometry={nodes.Mesh068_1.geometry} material={materials['vray Pen 23.003']} />
        <mesh geometry={nodes.Mesh068_2.geometry} material={materials['vray Pen 24.003']} />
      </group>
      <group castShadow position={[-3.475, 8.4, -0.703]} rotation={[-Math.PI, 0.004, -Math.PI]} scale={0.013}>
        <mesh geometry={nodes.Mesh069.geometry} material={materials['vray Apple id262.003']} />
        <mesh geometry={nodes.Mesh069_1.geometry} material={materials['vray Apple bn7.006']} />
        <mesh geometry={nodes.Mesh069_2.geometry} material={materials['vray Apple bn6.003']} />
      </group>
      <group castShadow position={[-1.759, 9.597, 2.549]} rotation={[-Math.PI, 0.004, -Math.PI]} scale={0.013}>
        <mesh geometry={nodes.Mesh070.geometry} material={materials['vray Apple id854.003']} />
        <mesh geometry={nodes.Mesh070_1.geometry} material={materials['vray Apple id4.003']} />
        <mesh geometry={nodes.Mesh070_2.geometry} material={materials['vray Apple id5.003']} />
        <mesh geometry={nodes.Mesh070_3.geometry} material={materials['vray Apple id6.003']} />
        <mesh geometry={nodes.Mesh070_4.geometry} material={materials['vray Apple id7.003']} />
        <mesh geometry={nodes.Mesh070_5.geometry} material={materials['vray Apple id8.003']} />
        <mesh geometry={nodes.Mesh070_6.geometry} material={materials['vray Apple id9.003']} />
        <mesh geometry={nodes.Mesh070_7.geometry} material={materials['vray Apple id10.003']} />
        <mesh geometry={nodes.Mesh070_8.geometry} material={materials['vray Apple id11.003']} />
        <mesh geometry={nodes.Mesh070_9.geometry} material={materials['vray Apple Display.003']} />
        <mesh geometry={nodes.Mesh070_10.geometry} material={materials['vray Apple id15.003']} />
        <mesh geometry={nodes.Mesh070_11.geometry} material={materials['vray Apple id16.003']} />
        <mesh geometry={nodes.Mesh070_12.geometry} material={materials['vray Apple id17.003']} />
      </group>
      <group castShadow position={[1.681, 8.563, 1.065]} rotation={[-Math.PI, 0.004, -Math.PI]} scale={0.013}>
        <mesh geometry={nodes.Mesh071.geometry} material={materials['vray Apple id42.003']} />
        <mesh geometry={nodes.Mesh071_1.geometry} material={materials['vray Apple id43.003']} />
        <mesh geometry={nodes.Mesh071_2.geometry} material={materials['vray Apple id44.003']} />
        <mesh geometry={nodes.Mesh071_3.geometry} material={materials['vray Apple id48.003']} />
        <mesh geometry={nodes.Mesh071_4.geometry} material={materials['vray Apple id49.003']} />
        <mesh geometry={nodes.Mesh071_5.geometry} material={materials['vray Apple id50.003']} />
        <mesh geometry={nodes.Mesh071_6.geometry} material={materials['vray Apple id51.003']} />
        <mesh geometry={nodes.Mesh071_7.geometry} material={materials['vray Apple id52.003']} />
        <mesh geometry={nodes.Mesh071_8.geometry} material={materials['vray Apple id53.003']} />
        <mesh geometry={nodes.Mesh071_9.geometry} material={materials['vray Apple id54.003']} />
        <mesh geometry={nodes.Mesh071_10.geometry} material={materials['vray Apple id55.003']} />
        <mesh geometry={nodes.Mesh071_11.geometry} material={materials['vray Apple id56.003']} />
        <mesh geometry={nodes.Mesh071_12.geometry} material={materials['vray Apple id57 Display.003']} />
        <mesh geometry={nodes.Mesh071_13.geometry} material={materials['vray Apple id58.003']} />
        <mesh geometry={nodes.Mesh071_14.geometry} material={materials['vray Apple id59.003']} />
        <mesh geometry={nodes.Mesh071_15.geometry} material={materials['vray Apple id60.003']} />
        <mesh geometry={nodes.Mesh071_16.geometry} material={materials['vray Apple id61.003']} />
        <mesh geometry={nodes.Mesh071_17.geometry} material={materials['vray Apple id62.003']} />
        <mesh geometry={nodes.Mesh071_18.geometry} material={materials['vray Apple id63.003']} />
        <mesh geometry={nodes.Mesh071_19.geometry} material={materials['vray Apple id64.003']} />
      </group>
      <group castShadow position={[1.714, 8.433, 1.041]} rotation={[-Math.PI, 0.004, -Math.PI]} scale={0.013}>
        <mesh geometry={nodes.Mesh072.geometry} material={materials['vray Power 3.003']} />
        <mesh geometry={nodes.Mesh072_1.geometry} material={materials['vray Power 4.003']} />
        <mesh geometry={nodes.Mesh072_2.geometry} material={materials['vray Power 5.003']} />
        <mesh geometry={nodes.Mesh072_3.geometry} material={materials['vray Power 8.003']} />
        <mesh geometry={nodes.Mesh072_4.geometry} material={materials['vray Apple id48.003']} />
        <mesh geometry={nodes.Mesh072_5.geometry} material={materials['vray Apple id58.003']} />
      </group>
      <group castShadow position={[1.136, 8.444, 3.911]} rotation={[-Math.PI, 0.004, -Math.PI]} scale={0.013}>
        <mesh geometry={nodes.Mesh073.geometry} material={materials['vray Apple id256.003']} />
        <mesh geometry={nodes.Mesh073_1.geometry} material={materials['vray Apple id257.003']} />
        <mesh geometry={nodes.Mesh073_2.geometry} material={materials['vray Apple id258.003']} />
        <mesh geometry={nodes.Mesh073_3.geometry} material={materials['vray Apple id259.003']} />
      </group>
      <group castShadow position={[0.416, 8.49, 2.381]} rotation={[-Math.PI, 0.004, -Math.PI]} scale={0.013}>
        <mesh geometry={nodes.Mesh074.geometry} material={materials['vray Apple id854.003']} />
        <mesh geometry={nodes.Mesh074_1.geometry} material={materials['vray Apple id8.003']} />
        <mesh geometry={nodes.Mesh074_2.geometry} material={materials['vray Apple id7.003']} />
        <mesh geometry={nodes.Mesh074_3.geometry} material={materials['vray Apple id251.003']} />
        <mesh geometry={nodes.Mesh074_4.geometry} material={materials['vray Apple bn7.007']} />
        <mesh geometry={nodes.Mesh074_5.geometry} material={materials['vray Apple bn6r.003']} />
        <mesh geometry={nodes.Mesh074_6.geometry} material={materials['vray Apple id252.003']} />
      </group>
      <group castShadow position={[0.794, 8.493, 1.837]} rotation={[-Math.PI, 0.004, -Math.PI]} scale={0.013}>
        <mesh geometry={nodes.Mesh075.geometry} material={materials['vray Apple id262.003']} />
        <mesh geometry={nodes.Mesh075_1.geometry} material={materials['vray Apple bn7.006']} />
        <mesh geometry={nodes.Mesh075_2.geometry} material={materials['vray Apple bn6.003']} />
      </group>
      <group castShadow position={[4.708, 8.415, -0.035]} rotation={[-Math.PI, 0.004, -Math.PI]} scale={0.013}>
        <mesh geometry={nodes.Mesh076.geometry} material={materials['vray Apple TV 3.003']} />
        <mesh geometry={nodes.Mesh076_1.geometry} material={materials['vray Apple TV 4.003']} />
        <mesh geometry={nodes.Mesh076_2.geometry} material={materials['vray Apple TV 5.003']} />
      </group>
      <group castShadow position={[-5.724, 8.548, 0.47]} rotation={[-Math.PI, 0.004, -Math.PI]} scale={0.013}>
        <mesh geometry={nodes.Mesh077.geometry} material={materials['vray Apple bn38.003']} />
        <mesh geometry={nodes.Mesh077_1.geometry} material={materials['vray Apple bn39.003']} />
        <mesh geometry={nodes.Mesh077_2.geometry} material={materials['vray Apple bn40.003']} />
      </group>
      <mesh castShadow geometry={nodes.Apple_id1995.geometry} material={materials['vray Apple id19.003']} position={[-5.786, 8.385, 0.444]} rotation={[-Math.PI, 0.004, -Math.PI]} scale={0.013} />
      <group castShadow position={[2.39, 8.472, -0.267]} rotation={[-Math.PI, 0.004, -Math.PI]} scale={0.013}>
        <mesh geometry={nodes.Mesh079.geometry} material={materials['vray Airpods 32.003']} />
        <mesh geometry={nodes.Mesh079_1.geometry} material={materials['vray Airpods 33.003']} />
        <mesh geometry={nodes.Mesh079_2.geometry} material={materials['vray Airpods 34.003']} />
        <mesh geometry={nodes.Mesh079_3.geometry} material={materials['vray Airpods 35.003']} />
        <mesh geometry={nodes.Mesh079_4.geometry} material={materials['vray Airpods 36.003']} />
      </group>
      <group castShadow position={[2.396, 8.475, 0.078]} rotation={[-Math.PI, 0.004, -Math.PI]} scale={0.013}>
        <mesh geometry={nodes.Mesh080.geometry} material={materials['vray Airpods 22.003']} />
        <mesh geometry={nodes.Mesh080_1.geometry} material={materials['vray Airpods 23.003']} />
        <mesh geometry={nodes.Mesh080_2.geometry} material={materials['vray Airpods 24.003']} />
        <mesh geometry={nodes.Mesh080_3.geometry} material={materials['vray Airpods 25.003']} />
        <mesh geometry={nodes.Mesh080_4.geometry} material={materials['vray Airpods 26.003']} />
      </group>
      <group castShadow position={[-6.656, 8.532, 2.402]} rotation={[-Math.PI, 0.004, -Math.PI]} scale={0.013}>
        <mesh geometry={nodes.Mesh081.geometry} material={materials['vray Galsses 911.003']} />
        <mesh geometry={nodes.Mesh081_1.geometry} material={materials['vray Galsses 912.003']} />
        <mesh geometry={nodes.Mesh081_2.geometry} material={materials['vray Galsses 912.003']} />
      </group>
      <group castShadow position={[4.76, 9.935, 3.549]} rotation={[-Math.PI, 0.004, -Math.PI]} scale={0.013}>
        <mesh geometry={nodes.Mesh082.geometry} material={materials['vray Apple Pro 3.001']} />
        <mesh geometry={nodes.Mesh082_1.geometry} material={materials['vray Apple Pro 4.001']} />
        <mesh geometry={nodes.Mesh082_2.geometry} material={materials['vray Apple Pro 7.001']} />
        <mesh geometry={nodes.Mesh082_3.geometry} material={materials['vray Apple Pro 10.001']} />
        <mesh geometry={nodes.Mesh082_4.geometry} material={materials['vray Apple Pro 11.001']} />
        <mesh geometry={nodes.Mesh082_5.geometry} material={materials['vray Apple Pro 12.001']} />
        <mesh geometry={nodes.Mesh082_6.geometry} material={materials['vray Apple Pro 13.001']} />
        <mesh geometry={nodes.Mesh082_7.geometry} material={materials['vray Apple Pro 14.001']} />
        <mesh geometry={nodes.Mesh082_8.geometry} material={materials['vray Apple Pro 15.001']} />
        <mesh geometry={nodes.Mesh082_9.geometry} material={materials['vray iphone 13 pro 11.001']} />
        <mesh geometry={nodes.Mesh082_10.geometry} material={materials['vray iphone 13 pro 15.001']} />
        <mesh geometry={nodes.Mesh082_11.geometry} material={materials['vray iphone 13 pro 16.001']} />
        <mesh geometry={nodes.Mesh082_12.geometry} material={materials['vray iphone 13 pro 23.001']} />
        <mesh geometry={nodes.Mesh082_13.geometry} material={materials['vray Apple Pro 20.001']} />
        <mesh geometry={nodes.Mesh082_14.geometry} material={materials['vray Apple Pro 21.001']} />
        <mesh geometry={nodes.Mesh082_15.geometry} material={materials['vray Apple Pro 22.001']} />
        <mesh geometry={nodes.Mesh082_16.geometry} material={materials['vray Apple Pro 23.001']} />
        <mesh geometry={nodes.Mesh082_17.geometry} material={materials['vray Apple Pro 24.001']} />
        <mesh geometry={nodes.Mesh082_18.geometry} material={materials['vray Apple Pro 42 Display.001']} />
      </group>
      <group castShadow position={[4.761, 9.766, 2.495]} rotation={[-Math.PI, 0.004, -Math.PI]} scale={0.013}>
        <mesh geometry={nodes.Mesh083.geometry} material={materials['vray Keyboard Apple 3.001']} />
        <mesh geometry={nodes.Mesh083_1.geometry} material={materials['vray Keyboard Apple 4.001']} />
        <mesh geometry={nodes.Mesh083_2.geometry} material={materials['vray Keyboard Apple 5.001']} />
        <mesh geometry={nodes.Mesh083_3.geometry} material={materials['vray Keyboard Apple 6.001']} />
        <mesh geometry={nodes.Mesh083_4.geometry} material={materials['vray Keyboard Apple 7.001']} />
        <mesh geometry={nodes.Mesh083_5.geometry} material={materials['vray Keyboard Apple 8.001']} />
        <mesh geometry={nodes.Mesh083_6.geometry} material={materials['vray Keyboard Apple 9.001']} />
        <mesh geometry={nodes.Mesh083_7.geometry} material={materials['vray Keyboard Apple 10.001']} />
      </group>
      <mesh castShadow geometry={nodes.Table_1.geometry} material={materials['vray Table 2.003']} position={[0.003, 8.274, 2.363]} rotation={[-Math.PI, 0.004, -Math.PI]} scale={0.013} />
      <group castShadow position={[7.111, 8.93, -0.697]} rotation={[-Math.PI, 0.004, -Math.PI]} scale={0.013}>
        <mesh geometry={nodes.Mesh085.geometry} material={materials['vray HomePod Mini 3.003']} />
        <mesh geometry={nodes.Mesh085_1.geometry} material={materials['vray HomePod Mini 4.003']} />
        <mesh geometry={nodes.Mesh085_2.geometry} material={materials['vray HomePod Mini 5.003']} />
      </group>
      <group castShadow position={[-5.969, 8.568, 4.122]} rotation={[-Math.PI, 0.004, -Math.PI]} scale={0.013}>
        <mesh geometry={nodes.Mesh086.geometry} material={materials['vray Headphones 3.003']} />
        <mesh geometry={nodes.Mesh086_1.geometry} material={materials['vray Headphones 4.003']} />
        <mesh geometry={nodes.Mesh086_2.geometry} material={materials['vray Headphones 5.003']} />
        <mesh geometry={nodes.Mesh086_3.geometry} material={materials['vray Headphones 9.003']} />
        <mesh geometry={nodes.Mesh086_4.geometry} material={materials['vray Headphones 10.003']} />
      </group>
      <group castShadow position={[-4.867, 8.381, 2.471]} rotation={[-Math.PI, 0.004, -Math.PI]} scale={0.013}>
        <mesh geometry={nodes.Mesh087.geometry} material={materials['vray Mastercard 3.003']} />
        <mesh geometry={nodes.Mesh087_1.geometry} material={materials['vray Mastercard 4.003']} />
        <mesh geometry={nodes.Mesh087_2.geometry} material={materials['vray Mastercard 5.003']} />
        <mesh geometry={nodes.Mesh087_3.geometry} material={materials['vray Mastercard 6.003']} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/table.glb')
